
  $(document).ready(function(){
    $("#button_01").click(function(){
      $("p").hide(500);
    });
  });
  $(document).ready(function(){
    $("#button_02").click(function(){
      $("#p_03").hide();
    });
  });
  $(document).ready(function(){
    $("#button_03").click(function(){
      $(".cp_01").hide();
    });
  });
  $(document).ready(function(){
    $("#button_04").click(function(){
      $("*").hide();
    });
  });
  $(document).ready(function(){
    $("#button_05").click(function(){
      $("[href]").hide();
    });
  });
  $(document).ready(function(){
    $("#button_06").click(function(){
      $("h1").hide();
    });
  });
  $(document).ready(function(){
    $("#button_07").click(function(){
      $("ul li:first").hide();
    });
  });
  $(document).ready(function(){
    $("#button_08").click(function(){
      $("ul li:first-child").hide();
    });
  });
  $(document).ready(function(){
    $("#button_09").click(function(){
      $(":button").hide();
    });
  });
  $(document).click(function(){
    $("#button_10").click(function(){
    $("p").toggle();
  });
});
$(document).ready(function(){
  $("#button_11").click(function(){
    $(".cp_01").toggle();
  });
});